"""
Module 6 - Suspicious Pattern Detection (PRD section 11 / section 16)

Four deterministic rules, no AI involved in detection (flags are only ever
handed to Module 8 for plain-language narration, never generated by the LLM):
  1. Broker / bridge rule
  2. Shared-attribute rule
  3. Dense-subgroup rule
  4. Repeated co-occurrence rule
"""

from collections import defaultdict
from itertools import combinations
from typing import Dict, List

import networkx as nx

from app.config import (
    BROKER_BETWEENNESS_PERCENTILE,
    DENSE_SUBGROUP_DENSITY_THRESHOLD,
    DENSE_SUBGROUP_MIN_SIZE,
    REPEATED_COOCCURRENCE_MIN_EVENTS,
)
from app.models import PatternFlag


def _percentile(values: List[float], pct: float) -> float:
    if not values:
        return 0.0
    s = sorted(values)
    idx = min(int(len(s) * pct), len(s) - 1)
    return s[idx]


def detect_broker_pattern(graph: nx.MultiGraph, centrality: Dict[str, Dict[str, float]]) -> List[PatternFlag]:
    """Entities with unusually high betweenness that bridge otherwise separate clusters."""
    flags: List[PatternFlag] = []
    if graph.number_of_nodes() < 3:
        return flags

    simple_graph = nx.Graph(graph)
    betweenness_values = [c["betweenness"] for c in centrality.values()]
    cutoff = _percentile(betweenness_values, BROKER_BETWEENNESS_PERCENTILE)

    try:
        articulation_points = set(nx.articulation_points(simple_graph))
    except Exception:
        articulation_points = set()

    for node_id, c in centrality.items():
        if c["betweenness"] > 0 and (c["betweenness"] >= cutoff or node_id in articulation_points):
            name = graph.nodes.get(node_id, {}).get("name", node_id)
            deg = simple_graph.degree(node_id)
            flags.append(
                PatternFlag(
                    pattern_type="broker",
                    entities_involved=[node_id],
                    evidence=(
                        f"High betweenness centrality ({c['betweenness']}) bridging otherwise "
                        f"separate parts of the network"
                        + (" (articulation point)" if node_id in articulation_points else "")
                    ),
                    severity="high" if node_id in articulation_points else "medium",
                    why=f"{name} connects otherwise separate network clusters.",
                    graph_evidence={"degree": deg, "betweenness": c["betweenness"], "is_articulation_point": node_id in articulation_points},
                    source_evidence=graph.nodes.get(node_id, {}).get("source_refs", []),
                )
            )
    return flags


def detect_shared_attribute_pattern(graph: nx.MultiGraph) -> List[PatternFlag]:
    """A PhoneNumber / Vehicle / Location node or shared attribute connected to 2+ distinct Person entities."""
    flags: List[PatternFlag] = []
    
    # 1. Shared resource nodes (PhoneNumber, Vehicle, Location connected to 2+ persons)
    for node_id, data in graph.nodes(data=True):
        if data.get("type") not in ("PhoneNumber", "Vehicle", "Location"):
            continue
        person_neighbors = [
            n for n in graph.neighbors(node_id) if graph.nodes[n].get("type") == "Person"
        ]
        distinct_persons = set(person_neighbors)
        if len(distinct_persons) >= 2:
            names = [graph.nodes.get(p, {}).get("name", p) for p in distinct_persons]
            flags.append(
                PatternFlag(
                    pattern_type="shared_attribute",
                    entities_involved=[node_id] + list(distinct_persons),
                    evidence=(
                        f"{data.get('name', node_id)} ({data.get('type')}) is linked to multiple "
                        f"distinct people: {', '.join(names)} - possible alias or shared resource"
                    ),
                    severity="high",
                    why=f"{data.get('name', node_id)} is linked to multiple distinct people ({', '.join(names)}), indicating a shared resource or burner.",
                    graph_evidence={"shared_resource": data.get("name", node_id), "distinct_persons_count": len(distinct_persons)},
                    source_evidence=data.get("source_refs", []),
                )
            )

    # 2. Shared attributes directly on Person nodes (same phone, mobile, IMEI, plate)
    phone_to_persons = {}
    imei_to_persons = {}
    plate_to_persons = {}

    for node_id, data in graph.nodes(data=True):
        if data.get("type") == "Person":
            attrs = data.get("attributes") or {}
            raw_phone = attrs.get("phone") or attrs.get("mobile")
            if raw_phone:
                for ph in str(raw_phone).split(","):
                    p_clean = ph.strip()
                    if p_clean:
                        phone_to_persons.setdefault(p_clean, []).append(node_id)
            imei = attrs.get("imei")
            if imei and str(imei).strip():
                imei_to_persons.setdefault(str(imei).strip(), []).append(node_id)
            plate = attrs.get("plate") or attrs.get("vehicle")
            if plate and str(plate).strip():
                plate_to_persons.setdefault(str(plate).strip(), []).append(node_id)

    # Flag shared phone numbers between persons
    for phone_val, pids in phone_to_persons.items():
        unique_pids = sorted(set(pids))
        if len(unique_pids) >= 2:
            names = [graph.nodes.get(p, {}).get("name", p) for p in unique_pids]
            # Avoid duplicate flag if a PhoneNumber node for this phone already flagged it
            already_flagged = any(phone_val in f.evidence for f in flags)
            if not already_flagged:
                flags.append(
                    PatternFlag(
                        pattern_type="shared_attribute",
                        entities_involved=unique_pids,
                        evidence=(
                            f"Phone Number {phone_val} is shared across multiple distinct suspects: "
                            f"{', '.join(names)} - shared tactical burner or alias identity"
                        ),
                        severity="high",
                        why=f"Phone number {phone_val} appears associated with multiple persons ({', '.join(names)}), suggesting possible coordination or shared device.",
                        graph_evidence={"attribute": "phone", "value": phone_val, "suspect_count": len(unique_pids)},
                        source_evidence=[f"Attribute match: phone={phone_val}"],
                    )
                )

    # Flag shared hardware IMEIs
    for imei_val, pids in imei_to_persons.items():
        unique_pids = sorted(set(pids))
        if len(unique_pids) >= 2:
            names = [graph.nodes.get(p, {}).get("name", p) for p in unique_pids]
            flags.append(
                PatternFlag(
                    pattern_type="shared_attribute",
                    entities_involved=unique_pids,
                    evidence=(
                        f"Device IMEI {imei_val} is shared by: {', '.join(names)} - "
                        f"handset handover or SIM-swapping anomaly"
                    ),
                    severity="high",
                    why=f"Device hardware identifier IMEI {imei_val} is linked to multiple individuals ({', '.join(names)}).",
                    graph_evidence={"attribute": "imei", "value": imei_val, "suspect_count": len(unique_pids)},
                    source_evidence=[f"Attribute match: imei={imei_val}"],
                )
            )

    # Flag shared vehicle plates
    for plate_val, pids in plate_to_persons.items():
        unique_pids = sorted(set(pids))
        if len(unique_pids) >= 2:
            names = [graph.nodes.get(p, {}).get("name", p) for p in unique_pids]
            already_flagged = any(plate_val in f.evidence for f in flags)
            if not already_flagged:
                flags.append(
                    PatternFlag(
                        pattern_type="shared_attribute",
                        entities_involved=unique_pids,
                        evidence=(
                            f"Vehicle Plate {plate_val} is operated by multiple suspects: "
                            f"{', '.join(names)} - shared tactical vehicle"
                        ),
                        severity="high",
                        why=f"Vehicle registration plate {plate_val} is shared across {', '.join(names)}.",
                        graph_evidence={"attribute": "plate", "value": plate_val, "suspect_count": len(unique_pids)},
                        source_evidence=[f"Attribute match: plate={plate_val}"],
                    )
                )

    return flags


def detect_dense_subgroup_pattern(graph: nx.MultiGraph) -> List[PatternFlag]:
    """Small connected components or tightly connected cliques with unusually high internal edge density (possible cell)."""
    flags: List[PatternFlag] = []
    simple_graph = nx.Graph(graph)
    seen_groups = set()

    # 1. Check isolated connected components
    for component in nx.connected_components(simple_graph):
        n = len(component)
        if n < DENSE_SUBGROUP_MIN_SIZE:
            continue
        subgraph = simple_graph.subgraph(component)
        max_edges = n * (n - 1) / 2
        density = subgraph.number_of_edges() / max_edges if max_edges else 0.0
        if density >= DENSE_SUBGROUP_DENSITY_THRESHOLD:
            fkey = frozenset(component)
            seen_groups.add(fkey)
            names = [graph.nodes.get(nid, {}).get("name", nid) for nid in component]
            flags.append(
                PatternFlag(
                    pattern_type="dense_subgroup",
                    entities_involved=list(component),
                    evidence=(
                        f"A tightly interconnected group of {n} entities ({', '.join(names)}) "
                        f"with edge density {round(density, 2)} - possible cell"
                    ),
                    severity="medium",
                    why=f"This group of {n} entities exhibits high internal edge density ({round(density, 2)}), indicating frequent internal interactions.",
                    graph_evidence={"size": n, "density": round(density, 3), "members": names},
                    source_evidence=[f"Internal cluster subgraph with density {round(density, 2)}"],
                )
            )

    # 2. Check maximal cliques of size >= DENSE_SUBGROUP_MIN_SIZE inside larger networks
    try:
        clique_count = 0
        for clique in nx.find_cliques(simple_graph):
            clique_count += 1
            if clique_count > 100:  # DoS guard: limit clique evaluation on large/dense graphs
                break
            if len(clique) >= DENSE_SUBGROUP_MIN_SIZE:
                fkey = frozenset(clique)
                if fkey not in seen_groups:
                    seen_groups.add(fkey)
                    names = [graph.nodes.get(nid, {}).get("name", nid) for nid in clique]
                    flags.append(
                        PatternFlag(
                            pattern_type="dense_subgroup",
                            entities_involved=list(clique),
                            evidence=(
                                f"A tightly interconnected operating clique of {len(clique)} entities ({', '.join(names)}) "
                                f"with edge density 1.0 - possible operating cell"
                            ),
                            severity="high",
                            why=f"All {len(clique)} entities in this clique are mutually connected with density 1.0.",
                            graph_evidence={"size": len(clique), "density": 1.0, "members": names, "type": "maximal_clique"},
                            source_evidence=[f"Complete maximal subgraph of {len(clique)} nodes"],
                        )
                    )
    except Exception:
        pass

    return flags


def detect_repeated_cooccurrence_pattern(graph: nx.MultiGraph) -> List[PatternFlag]:
    """Two Person entities that co-occur (share an Event neighbor or an event_id-tagged edge) 2+ times."""
    flags: List[PatternFlag] = []

    # Map event identifier -> set of Person node ids linked to it
    event_to_people: Dict[str, set] = defaultdict(set)

    # (a) explicit Event entities in the graph
    for node_id, data in graph.nodes(data=True):
        if data.get("type") == "Event":
            for neighbor in graph.neighbors(node_id):
                if graph.nodes.get(neighbor, {}).get("type") == "Person":
                    event_to_people[node_id].add(neighbor)

    # (b) edges tagged with an event_id even without an Event node (e.g. structured import rows)
    for u, v, data in graph.edges(data=True):
        event_id = data.get("event_id")
        if not event_id:
            continue
        event_ids = [e.strip() for e in str(event_id).split(";") if e.strip()]
        for eid in event_ids:
            if graph.nodes.get(u, {}).get("type") == "Person":
                event_to_people[eid].add(u)
            if graph.nodes.get(v, {}).get("type") == "Person":
                event_to_people[eid].add(v)

    pair_event_count: Dict[frozenset, set] = defaultdict(set)
    for event_id, people in event_to_people.items():
        for a, b in combinations(sorted(people), 2):
            pair_event_count[frozenset((a, b))].add(event_id)

    for pair, events in pair_event_count.items():
        if len(events) >= REPEATED_COOCCURRENCE_MIN_EVENTS:
            a, b = tuple(pair)
            name_a = graph.nodes.get(a, {}).get("name", a)
            name_b = graph.nodes.get(b, {}).get("name", b)
            flags.append(
                PatternFlag(
                    pattern_type="repeated_cooccurrence",
                    entities_involved=[a, b],
                    evidence=(
                        f"{name_a} and {name_b} co-occur across {len(events)} distinct events - "
                        f"repeated contact pattern worth review"
                    ),
                    severity="medium",
                    why=f"{name_a} and {name_b} repeatedly co-occur across {len(events)} events or transactions.",
                    graph_evidence={"cooccurrence_count": len(events), "event_ids": list(events)[:5]},
                    source_evidence=[f"Shared event records: {', '.join(list(events)[:3])}"],
                )
            )
    return flags


def detect_all_patterns(graph: nx.MultiGraph, centrality: Dict[str, Dict[str, float]]) -> List[PatternFlag]:
    return (
        detect_broker_pattern(graph, centrality)
        + detect_shared_attribute_pattern(graph)
        + detect_dense_subgroup_pattern(graph)
        + detect_repeated_cooccurrence_pattern(graph)
    )
