"""
Module 6 - Suspicious Pattern Detection (PRD section 11 / section 16)

Four deterministic rules, no AI involved in detection (flags are only ever
handed to Module 8 for plain-language narration, never generated by the LLM):
  1. Broker / bridge rule
  2. Shared-attribute rule
  3. Dense-subgroup rule
  4. Repeated co-occurrence rule
"""

from collections import defaultdict
from itertools import combinations
from typing import Dict, List

import networkx as nx

from app.config import (
    BROKER_BETWEENNESS_PERCENTILE,
    DENSE_SUBGROUP_DENSITY_THRESHOLD,
    DENSE_SUBGROUP_MIN_SIZE,
    REPEATED_COOCCURRENCE_MIN_EVENTS,
)
from app.models import PatternFlag


def _percentile(values: List[float], pct: float) -> float:
    if not values:
        return 0.0
    s = sorted(values)
    idx = min(int(len(s) * pct), len(s) - 1)
    return s[idx]


def detect_broker_pattern(graph: nx.MultiGraph, centrality: Dict[str, Dict[str, float]]) -> List[PatternFlag]:
    """Entities with unusually high betweenness that bridge otherwise separate clusters."""
    flags: List[PatternFlag] = []
    if graph.number_of_nodes() < 3:
        return flags

    simple_graph = nx.Graph(graph)
    betweenness_values = [c["betweenness"] for c in centrality.values()]
    cutoff = _percentile(betweenness_values, BROKER_BETWEENNESS_PERCENTILE)

    try:
        articulation_points = set(nx.articulation_points(simple_graph))
    except Exception:
        articulation_points = set()

    for node_id, c in centrality.items():
        if c["betweenness"] > 0 and (c["betweenness"] >= cutoff or node_id in articulation_points):
            name = graph.nodes.get(node_id, {}).get("name", node_id)
            flags.append(
                PatternFlag(
                    pattern_type="broker",
                    entities_involved=[node_id],
                    evidence=(
                        f"High betweenness centrality ({c['betweenness']}) bridging otherwise "
                        f"separate parts of the network"
                        + (" (articulation point)" if node_id in articulation_points else "")
                    ),
                    severity="high" if node_id in articulation_points else "medium",
                )
            )
    return flags


def detect_shared_attribute_pattern(graph: nx.MultiGraph) -> List[PatternFlag]:
    """A PhoneNumber / Vehicle / Location node connected to 2+ distinct Person entities."""
    flags: List[PatternFlag] = []
    for node_id, data in graph.nodes(data=True):
        if data.get("type") not in ("PhoneNumber", "Vehicle", "Location"):
            continue
        person_neighbors = [
            n for n in graph.neighbors(node_id) if graph.nodes[n].get("type") == "Person"
        ]
        distinct_persons = set(person_neighbors)
        if len(distinct_persons) >= 2:
            names = [graph.nodes.get(p, {}).get("name", p) for p in distinct_persons]
            flags.append(
                PatternFlag(
                    pattern_type="shared_attribute",
                    entities_involved=[node_id] + list(distinct_persons),
                    evidence=(
                        f"{data.get('name', node_id)} ({data.get('type')}) is linked to multiple "
                        f"distinct people: {', '.join(names)} - possible alias or shared resource"
                    ),
                    severity="high",
                )
            )
    return flags


def detect_dense_subgroup_pattern(graph: nx.MultiGraph) -> List[PatternFlag]:
    """Small connected components or tightly connected cliques with unusually high internal edge density (possible cell)."""
    flags: List[PatternFlag] = []
    simple_graph = nx.Graph(graph)
    seen_groups = set()

    # 1. Check isolated connected components
    for component in nx.connected_components(simple_graph):
        n = len(component)
        if n < DENSE_SUBGROUP_MIN_SIZE:
            continue
        subgraph = simple_graph.subgraph(component)
        max_edges = n * (n - 1) / 2
        density = subgraph.number_of_edges() / max_edges if max_edges else 0.0
        if density >= DENSE_SUBGROUP_DENSITY_THRESHOLD:
            fkey = frozenset(component)
            seen_groups.add(fkey)
            names = [graph.nodes.get(nid, {}).get("name", nid) for nid in component]
            flags.append(
                PatternFlag(
                    pattern_type="dense_subgroup",
                    entities_involved=list(component),
                    evidence=(
                        f"A tightly interconnected group of {n} entities ({', '.join(names)}) "
                        f"with edge density {round(density, 2)} - possible cell"
                    ),
                    severity="medium",
                )
            )

    # 2. Check maximal cliques of size >= DENSE_SUBGROUP_MIN_SIZE inside larger networks
    try:
        for clique in nx.find_cliques(simple_graph):
            if len(clique) >= DENSE_SUBGROUP_MIN_SIZE:
                fkey = frozenset(clique)
                if fkey not in seen_groups:
                    seen_groups.add(fkey)
                    names = [graph.nodes.get(nid, {}).get("name", nid) for nid in clique]
                    flags.append(
                        PatternFlag(
                            pattern_type="dense_subgroup",
                            entities_involved=list(clique),
                            evidence=(
                                f"A tightly interconnected operating clique of {len(clique)} entities ({', '.join(names)}) "
                                f"with edge density 1.0 - possible operating cell"
                            ),
                            severity="high",
                        )
                    )
    except Exception:
        pass

    return flags


def detect_repeated_cooccurrence_pattern(graph: nx.MultiGraph) -> List[PatternFlag]:
    """Two Person entities that co-occur (share an Event neighbor or an event_id-tagged edge) 2+ times."""
    flags: List[PatternFlag] = []

    # Map event identifier -> set of Person node ids linked to it
    event_to_people: Dict[str, set] = defaultdict(set)

    # (a) explicit Event entities in the graph
    for node_id, data in graph.nodes(data=True):
        if data.get("type") == "Event":
            for neighbor in graph.neighbors(node_id):
                if graph.nodes.get(neighbor, {}).get("type") == "Person":
                    event_to_people[node_id].add(neighbor)

    # (b) edges tagged with an event_id even without an Event node (e.g. structured import rows)
    for u, v, data in graph.edges(data=True):
        event_id = data.get("event_id")
        if not event_id:
            continue
        event_ids = [e.strip() for e in str(event_id).split(";") if e.strip()]
        for eid in event_ids:
            if graph.nodes.get(u, {}).get("type") == "Person":
                event_to_people[eid].add(u)
            if graph.nodes.get(v, {}).get("type") == "Person":
                event_to_people[eid].add(v)

    pair_event_count: Dict[frozenset, set] = defaultdict(set)
    for event_id, people in event_to_people.items():
        for a, b in combinations(sorted(people), 2):
            pair_event_count[frozenset((a, b))].add(event_id)

    for pair, events in pair_event_count.items():
        if len(events) >= REPEATED_COOCCURRENCE_MIN_EVENTS:
            a, b = tuple(pair)
            name_a = graph.nodes.get(a, {}).get("name", a)
            name_b = graph.nodes.get(b, {}).get("name", b)
            flags.append(
                PatternFlag(
                    pattern_type="repeated_cooccurrence",
                    entities_involved=[a, b],
                    evidence=(
                        f"{name_a} and {name_b} co-occur across {len(events)} distinct events - "
                        f"repeated contact pattern worth review"
                    ),
                    severity="medium",
                )
            )
    return flags


def detect_all_patterns(graph: nx.MultiGraph, centrality: Dict[str, Dict[str, float]]) -> List[PatternFlag]:
    return (
        detect_broker_pattern(graph, centrality)
        + detect_shared_attribute_pattern(graph)
        + detect_dense_subgroup_pattern(graph)
        + detect_repeated_cooccurrence_pattern(graph)
    )
