import React from 'react';
import { 
  Sparkles, 
  ShieldAlert, 
  RotateCw, 
  Printer, 
  CheckCircle2, 
  Eye, 
  Info,
  Scale
} from 'lucide-react';

export default function SummaryView({ 
  summaryData, 
  loading, 
  onRefresh, 
  onInspectEntity 
}) {
  const summary = summaryData?.summary || '';
  const watchList = summaryData?.entities_to_watch || [];

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      
      {/* Strict Legal & AI Boundary Banner */}
      <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-4 flex items-start space-x-3 text-xs text-amber-200/90">
        <Scale className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <strong className="text-amber-300 font-bold block mb-0.5">
            AI-Assisted Investigation Briefing (Investigator Advisory)
          </strong>
          This natural-language synthesis is generated by Groq LLM strictly using the mathematical graph centrality rankings and pattern flags computed above. 
          The AI does not decide guilt, determine threat, or fabricate facts. All outputs require independent human investigator verification.
        </div>
      </div>

      {/* Main Briefing Card */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6">
        
        {/* Card Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center space-x-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-amber-500/20 to-orange-500/20 border border-amber-500/30 flex items-center justify-center text-amber-300">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-100 text-base">Executive Intelligence Briefing</h3>
              <p className="text-xs text-slate-400">Automated Plain-English Case Assessment</p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={onRefresh}
              disabled={loading}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold border border-slate-700 transition disabled:opacity-50"
            >
              <RotateCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
              <span>{loading ? 'Generating...' : 'Re-generate'}</span>
            </button>
            <button
              onClick={() => window.print()}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold border border-slate-700 transition"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
          </div>
        </div>

        {/* Narrative Section */}
        {loading ? (
          <div className="py-12 flex flex-col items-center justify-center space-y-3">
            <div className="w-8 h-8 border-2 border-amber-400 border-t-transparent rounded-full animate-spin" />
            <p className="text-xs text-slate-400 font-mono">Synthesizing network topology with Groq LLM...</p>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="prose prose-invert max-w-none text-slate-300 text-sm leading-relaxed bg-slate-950/50 p-5 rounded-xl border border-slate-800 font-sans whitespace-pre-line">
              {summary || 'No summary generated yet. Click Re-generate to produce an intelligence briefing.'}
            </div>

            {/* Entities to Watch Checklist */}
            {watchList.length > 0 && (
              <div className="space-y-3 pt-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center">
                  <Eye className="w-4 h-4 mr-1.5 text-cyan-400" />
                  Key Entities for Immediate Surveillance / Inquiry:
                </h4>
                <div className="grid sm:grid-cols-2 gap-2.5">
                  {watchList.map((item, idx) => (
                    <div 
                      key={idx}
                      className="flex items-center justify-between p-3 rounded-xl bg-slate-800/40 border border-slate-700/60 text-xs"
                    >
                      <div className="flex items-center space-x-2">
                        <span className="w-2 h-2 rounded-full bg-cyan-400" />
                        <span className="font-semibold text-slate-200">{item}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

      </div>

    </div>
  );
}
