"""initial_schema

Revision ID: c630647a9845
Revises: 
Create Date: 2026-09-19 20:30:50.859383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c630647a9845'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_integrity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_verified_at', sa.String(length=64), nullable=False),
    sa.Column('verified_by', sa.String(length=128), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('broken_record_id', sa.String(length=64), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=128), nullable=True),
    sa.Column('current_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('case_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investigation_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=64), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.Column('last_login', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('api_token', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('case_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('case_role', sa.String(length=64), nullable=False),
    sa.Column('assigned_by', sa.String(length=128), nullable=True),
    sa.Column('assigned_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id', name='uq_case_user')
    )
    op.create_index(op.f('ix_case_users_case_id'), 'case_users', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_users_user_id'), 'case_users', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=64), nullable=True),
    sa.Column('aliases_json', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('source_refs_json', sa.Text(), nullable=True),
    sa.Column('community_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=256), nullable=True),
    sa.Column('source_record', sa.String(length=128), nullable=True),
    sa.Column('validation_status', sa.String(length=64), nullable=True),
    sa.Column('is_merged', sa.Boolean(), nullable=True),
    sa.Column('merged_into_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'entity_id', name='uq_case_entity')
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_entities_email'), 'entities', ['email'], unique=False)
    op.create_index(op.f('ix_entities_entity_id'), 'entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entities_evidence_id'), 'entities', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_entities_normalized_name'), 'entities', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_entities_phone'), 'entities', ['phone'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index(op.f('ix_entities_vehicle_plate'), 'entities', ['vehicle_plate'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('normalized_alias', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'entity_id', 'normalized_alias', name='uq_case_entity_alias')
    )
    op.create_index(op.f('ix_entity_aliases_case_id'), 'entity_aliases', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_normalized_alias'), 'entity_aliases', ['normalized_alias'], unique=False)
    op.create_table('entity_merges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merge_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.String(length=64), nullable=False),
    sa.Column('source_entity_name', sa.String(length=256), nullable=False),
    sa.Column('target_entity_id', sa.String(length=64), nullable=False),
    sa.Column('target_entity_name', sa.String(length=256), nullable=False),
    sa.Column('performed_by', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'merge_id', name='uq_case_merge')
    )
    op.create_index(op.f('ix_entity_merges_case_id'), 'entity_merges', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_merges_merge_id'), 'entity_merges', ['merge_id'], unique=False)
    op.create_index(op.f('ix_entity_merges_timestamp'), 'entity_merges', ['timestamp'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('acquisition_timestamp', sa.String(length=64), nullable=True),
    sa.Column('processing_timestamp', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('ai_model_version', sa.String(length=64), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=64), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'evidence_id', name='uq_case_evidence')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256_hash'), 'evidence', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_evidence_uploaded_at'), 'evidence', ['uploaded_at'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('record_index', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_case_id'), 'evidence_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_evidence_id'), 'evidence_records', ['evidence_id'], unique=False)
    op.create_table('investigation_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_category', sa.String(length=64), nullable=True),
    sa.Column('why_flagged_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'lead_id', name='uq_case_lead')
    )
    op.create_index(op.f('ix_investigation_leads_case_id'), 'investigation_leads', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_leads_created_at'), 'investigation_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigation_leads_entity_id'), 'investigation_leads', ['entity_id'], unique=False)
    op.create_index(op.f('ix_investigation_leads_lead_id'), 'investigation_leads', ['lead_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('relationship_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'note_id', name='uq_case_note')
    )
    op.create_index(op.f('ix_notes_case_id'), 'notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notes_evidence_id'), 'notes', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_notes_note_id'), 'notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_notes_relationship_id'), 'notes', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_notes_timestamp'), 'notes', ['timestamp'], unique=False)
    op.create_table('pattern_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('pattern_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('entities_involved_json', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'finding_id', name='uq_case_pattern')
    )
    op.create_index(op.f('ix_pattern_findings_case_id'), 'pattern_findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_pattern_findings_finding_id'), 'pattern_findings', ['finding_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rel_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=128), nullable=False),
    sa.Column('is_directed', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.String(length=64), nullable=True),
    sa.Column('confidence_reasons_json', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=256), nullable=True),
    sa.Column('source_record', sa.String(length=128), nullable=True),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=64), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('suspected_crime', sa.String(length=256), nullable=True),
    sa.Column('crime_category', sa.String(length=128), nullable=True),
    sa.Column('legal_statutes_json', sa.Text(), nullable=True),
    sa.Column('crime_severity', sa.String(length=64), nullable=True),
    sa.Column('crime_rationale', sa.Text(), nullable=True),
    sa.Column('actionable_recommendations_json', sa.Text(), nullable=True),
    sa.Column('evidentiary_sufficiency', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'rel_id', name='uq_case_rel')
    )
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_relationships_evidence_id'), 'relationships', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_relationships_rel_id'), 'relationships', ['rel_id'], unique=False)
    op.create_index(op.f('ix_relationships_relation_type'), 'relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('validation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('name_or_pair', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.String(length=64), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'record_id', name='uq_case_valrec')
    )
    op.create_index(op.f('ix_validation_records_case_id'), 'validation_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_validation_records_created_at'), 'validation_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_validation_records_record_id'), 'validation_records', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_records_record_id'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_created_at'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_case_id'), table_name='validation_records')
    op.drop_table('validation_records')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relation_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_rel_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_evidence_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pattern_findings_finding_id'), table_name='pattern_findings')
    op.drop_index(op.f('ix_pattern_findings_case_id'), table_name='pattern_findings')
    op.drop_table('pattern_findings')
    op.drop_index(op.f('ix_notes_timestamp'), table_name='notes')
    op.drop_index(op.f('ix_notes_relationship_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_note_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_evidence_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_case_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_investigation_leads_lead_id'), table_name='investigation_leads')
    op.drop_index(op.f('ix_investigation_leads_entity_id'), table_name='investigation_leads')
    op.drop_index(op.f('ix_investigation_leads_created_at'), table_name='investigation_leads')
    op.drop_index(op.f('ix_investigation_leads_case_id'), table_name='investigation_leads')
    op.drop_table('investigation_leads')
    op.drop_index(op.f('ix_evidence_records_evidence_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_case_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_evidence_uploaded_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_sha256_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_merges_timestamp'), table_name='entity_merges')
    op.drop_index(op.f('ix_entity_merges_merge_id'), table_name='entity_merges')
    op.drop_index(op.f('ix_entity_merges_case_id'), table_name='entity_merges')
    op.drop_table('entity_merges')
    op.drop_index(op.f('ix_entity_aliases_normalized_alias'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_case_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_entities_vehicle_plate'), table_name='entities')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_phone'), table_name='entities')
    op.drop_index(op.f('ix_entities_normalized_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_evidence_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_email'), table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_case_users_user_id'), table_name='case_users')
    op.drop_index(op.f('ix_case_users_case_id'), table_name='case_users')
    op.drop_table('case_users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('audit_integrity')
    # ### end Alembic commands ###
